#!/usr/bin/env bash
set -euo pipefail

CSV="${1:-/etc/app-map.csv}"
STATE_DIR="/var/lib/vps-bootstrap"
NGINX_AVAIL="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"
PROJECT_AUTH_DIR="/etc/nginx/project-auth"
MARKER="# generated by vps-bootstrap"
MANIFEST="${STATE_DIR}/app-sync.manifest"
ACME_ROOT="/var/www/html"
CUSTOM_CERT_ROOT="/etc/vps-custom-certs/projects"
PROJECT_META_DIR="/etc/vps-projects"
SKIP_ACME="${APP_SYNC_SKIP_ACME:-0}"

mkdir -p "${STATE_DIR}"

declare -A desired_domains=()
declare -A proxy_routes_by_domain=()
declare -a desired_list=()

meta_env_value() {
  local file="$1"
  local key="$2"
  awk -F= -v key="${key}" '$1 == key { sub(/^[^=]*=/, ""); gsub(/\r/, ""); print; exit }' "${file}" 2>/dev/null || true
}

append_project_domains() {
  local meta
  local -a meta_files=()
  local domain
  local port
  local type
  local https
  local proxy_routes_json
  local previous_meta
  local -A domain_owner=()

  [[ -d "${PROJECT_META_DIR}" ]] || return 0
  while IFS= read -r -d '' meta; do
    meta_files+=("${meta}")
  done < <(find "${PROJECT_META_DIR}" -maxdepth 1 -type f -name '*.env' -print0 2>/dev/null)

  if [[ ${#meta_files[@]} -gt 1 ]]; then
    mapfile -t meta_files < <(
      for meta in "${meta_files[@]}"; do
        printf '%s\t%s\n' "$(stat -c '%Y' "${meta}" 2>/dev/null || printf '0')" "${meta}"
      done | sort -n -k1,1 -k2,2 | cut -f2-
    )
  fi

  for meta in "${meta_files[@]}"; do
    domain="$(meta_env_value "${meta}" APP_DOMAIN | tr '[:upper:]' '[:lower:]')"
    port="$(meta_env_value "${meta}" APP_PORT)"
    type="$(meta_env_value "${meta}" APP_TYPE)"
    https="$(meta_env_value "${meta}" APP_HTTPS)"
    proxy_routes_json="$(meta_env_value "${meta}" APP_PROXY_ROUTES_JSON)"
    [[ -n "${domain}" && -n "${port}" ]] || continue
    previous_meta="${domain_owner[$domain]:-}"
    if [[ -n "${previous_meta}" && "${previous_meta}" != "${meta}" ]]; then
      echo "[WARN] Domain ${domain} is claimed by multiple projects; using ${meta} because it was touched most recently" >&2
    fi
    domain_owner["${domain}"]="${meta}"
    proxy_routes_by_domain["${domain}"]="${proxy_routes_json}"
    printf '%s,%s,%s,%s\n' "${domain}" "${port}" "${type:-node}" "${https:-yes}"
    while IFS=$'\t' read -r extra_domain extra_port extra_type extra_https; do
      extra_domain="$(printf '%s' "${extra_domain}" | tr '[:upper:]' '[:lower:]')"
      [[ -n "${extra_domain:-}" && -n "${extra_port:-}" ]] || continue
      proxy_routes_by_domain["${extra_domain}"]="${proxy_routes_json}"
      printf '%s,%s,%s,%s\n' "${extra_domain}" "${extra_port}" "${extra_type:-${type:-node}}" "${extra_https:-${https:-yes}}"
    done < <(APP_DOMAIN="${domain}" APP_PORT="${port}" APP_TYPE="${type:-node}" APP_HTTPS="${https:-yes}" python3 - "${meta}" <<'PY'
import json
import os
import sys

meta_path = sys.argv[1]
raw = ""
try:
    with open(meta_path, "r", encoding="utf-8", errors="surrogateescape") as handle:
        for line in handle:
            line = line.rstrip("\n")
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            if key.strip() == "APP_DOMAIN_BINDINGS_JSON":
                raw = value.strip()
                break
except OSError:
    raise SystemExit(0)

if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ("'", '"'):
    raw = raw[1:-1]

if not raw.strip():
    raise SystemExit(0)

try:
    data = json.loads(raw)
except Exception:
    raise SystemExit(0)

primary_domain = os.environ.get("APP_DOMAIN", "")
primary_domain = primary_domain.strip().lower()
for item in data if isinstance(data, list) else []:
    if not isinstance(item, dict):
        continue
    dom = str(item.get("domain", "")).strip().lower()
    if not dom or dom == primary_domain:
        continue
    port = str(item.get("port", "")).strip() or os.environ.get("APP_PORT", "")
    typ = str(item.get("type", "")).strip() or os.environ.get("APP_TYPE", "node")
    https = str(item.get("https", "")).strip() or os.environ.get("APP_HTTPS", "yes")
    if dom and port:
        print(f"{dom}\t{port}\t{typ}\t{https}")
PY
    )
  done
}

default_domain_for() {
  local domain="$1"
  if [[ "${domain}" != *.*.* ]]; then
    printf ''
    return 0
  fi
  printf '%s' "${domain#*.}"
}

auth_block_for_domain() {
  local domain="$1"
  local auth_file="${PROJECT_AUTH_DIR}/${domain}.htpasswd"
  if [[ -s "${auth_file}" ]]; then
    cat <<EOF
    auth_basic "Project access";
    auth_basic_user_file ${auth_file};
EOF
  fi
}

render_http_only() {
  local domain="$1"
  local port="$2"
  local auth_block="$3"
  local extra_blocks="${4:-}"
  cat <<EOF2
${MARKER}
server {
    listen 80;
    server_name ${domain};
    client_max_body_size 50m;
${auth_block}
    location /.well-known/acme-challenge/ {
        auth_basic off;
        root ${ACME_ROOT};
    }

${extra_blocks}

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
    }
}
EOF2
}

render_https() {
  local domain="$1"
  local port="$2"
  local auth_block="$3"
  local cert_path="$4"
  local key_path="$5"
  local extra_blocks="${6:-}"
  cat <<EOF2
${MARKER}
server {
    listen 80;
    server_name ${domain};
    client_max_body_size 50m;

    location /.well-known/acme-challenge/ {
        auth_basic off;
        root ${ACME_ROOT};
    }

${extra_blocks}

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name ${domain};
    client_max_body_size 50m;
${auth_block}
    ssl_certificate ${cert_path};
    ssl_certificate_key ${key_path};

    location /.well-known/acme-challenge/ {
        auth_basic off;
        root ${ACME_ROOT};
    }

${extra_blocks}

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
    }
}
EOF2
}

render_proxy_route_blocks() {
  local raw="${1:-}"
  local fallback_port="${2:-}"

  [[ -n "${raw}" ]] || return 0
  python3 - "${raw}" "${fallback_port}" <<'PY'
import json
import sys

raw = sys.argv[1] or ""
fallback_port = sys.argv[2] or ""
if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ("'", '"'):
    raw = raw[1:-1]
try:
    data = json.loads(raw)
except Exception:
    raise SystemExit(0)

if not isinstance(data, list):
    raise SystemExit(0)

common = """        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection \"upgrade\";
        proxy_redirect off;"""

blocks = []
for item in data:
    if not isinstance(item, dict):
        continue
    path = str(item.get("path", "")).strip()
    port = str(item.get("port", "")).strip() or fallback_port
    route_type = str(item.get("type", "prefix")).strip().lower() or "prefix"
    if not path:
        continue
    if not path.startswith("/"):
        path = "/" + path
    if not port.isdigit():
        continue
    if route_type not in ("prefix", "exact"):
        route_type = "prefix"
    location = f"location = {path}" if route_type == "exact" else f"location ^~ {path}"
    blocks.append(
        f"""    {location} {{
        proxy_pass http://127.0.0.1:{port};
{common}
    }}"""
    )

if blocks:
    print("\n\n".join(blocks))
PY
}

cert_email_args=()
if [[ -n "${ACME_EMAIL:-}" ]]; then
  cert_email_args=(-m "${ACME_EMAIL}")
else
  cert_email_args=(--register-unsafely-without-email)
fi

SOURCE_CSV="$(mktemp)"
NORMALIZED_CSV="$(mktemp)"
trap 'rm -f "${SOURCE_CSV}" "${NORMALIZED_CSV}"' EXIT
if [[ -f "${CSV}" ]]; then
  cat "${CSV}" > "${SOURCE_CSV}"
else
  printf 'domain,port,type,https\n' > "${SOURCE_CSV}"
fi
append_project_domains >> "${SOURCE_CSV}"
awk -F, -v OFS=, '
  NR == 1 && $1 == "domain" { next }
  $1 ~ /^#/ || $1 == "" { next }
  {
    gsub(/\r/, "", $1);
    gsub(/\r/, "", $2);
    gsub(/\r/, "", $3);
    gsub(/\r/, "", $4);
    domain = tolower($1);
    if (!seen[domain]++) {
      order[++count] = domain;
    }
    rows[domain] = domain OFS $2 OFS $3 OFS $4;
  }
  END {
    print "domain,port,type,https";
    for (i = 1; i <= count; i++) {
      domain = order[i];
      if (!printed[domain]++) {
        print rows[domain];
      }
    }
  }
' "${SOURCE_CSV}" > "${NORMALIZED_CSV}"

install -m 0644 "${NORMALIZED_CSV}" "${CSV}"

while IFS=, read -r domain port type https; do
  [[ -z "${domain:-}" ]] && continue
  [[ "${domain}" == "domain" ]] && continue
  [[ "${domain:0:1}" == "#" ]] && continue

  domain="${domain//$'\r'/}"
  port="${port//$'\r'/}"
  type="${type//$'\r'/}"
  https="${https//$'\r'/}"

  if ! [[ "${domain}" =~ ^[A-Za-z0-9.-]+$ ]]; then
    echo "[WARN] Skipping invalid domain: ${domain}" >&2
    continue
  fi

  if ! [[ "${port}" =~ ^[0-9]+$ ]]; then
    echo "[WARN] Skipping ${domain} due to invalid port: ${port}" >&2
    continue
  fi

  desired_domains["${domain}"]=1
  desired_list+=("${domain}")

  conf="${NGINX_AVAIL}/${domain}.conf"
  tmp="$(mktemp)"
  auth_block="$(auth_block_for_domain "${domain}")"
  extra_blocks="$(render_proxy_route_blocks "${proxy_routes_by_domain[$domain]:-}" "${port}")"
  custom_cert_dir="${CUSTOM_CERT_ROOT}/${domain}"
  custom_cert="${custom_cert_dir}/fullchain.pem"
  custom_key="${custom_cert_dir}/privkey.pem"
  fallback_domain="$(default_domain_for "${domain}")"
  fallback_cert_dir="${CUSTOM_CERT_ROOT}/server/${fallback_domain}"
  fallback_cert="${fallback_cert_dir}/fullchain.pem"
  fallback_key="${fallback_cert_dir}/privkey.pem"

  if [[ "${https,,}" == "yes" ]]; then
    cert_ready="no"
    cert_source=""
    if [[ -s "${custom_cert}" && -s "${custom_key}" ]]; then
      cert_ready="yes"
      cert_source="custom"
    elif [[ -n "${fallback_domain}" && -s "${fallback_cert}" && -s "${fallback_key}" ]]; then
      cert_ready="yes"
      cert_source="default-domain"
    elif [[ "${SKIP_ACME}" != "1" && ! -s "/etc/letsencrypt/live/${domain}/fullchain.pem" ]]; then
      if certbot certonly \
        --webroot \
        -w "${ACME_ROOT}" \
        -d "${domain}" \
        --non-interactive \
        --agree-tos \
        "${cert_email_args[@]}" \
        --keep-until-expiring; then
        cert_ready="yes"
        cert_source="letsencrypt"
      else
        echo "[WARN] TLS issuance failed for ${domain}; keeping HTTP only for now" >&2
      fi
    else
      cert_ready="yes"
      cert_source="letsencrypt"
    fi

    if [[ "${cert_ready}" == "yes" ]]; then
      if [[ "${cert_source:-}" == "custom" ]]; then
        render_https "${domain}" "${port}" "${auth_block}" "${custom_cert}" "${custom_key}" "${extra_blocks}" > "${tmp}"
      elif [[ "${cert_source:-}" == "default-domain" ]]; then
        render_https "${domain}" "${port}" "${auth_block}" "${fallback_cert}" "${fallback_key}" "${extra_blocks}" > "${tmp}"
      else
        render_https "${domain}" "${port}" "${auth_block}" "/etc/letsencrypt/live/${domain}/fullchain.pem" "/etc/letsencrypt/live/${domain}/privkey.pem" "${extra_blocks}" > "${tmp}"
      fi
    else
      render_http_only "${domain}" "${port}" "${auth_block}" "${extra_blocks}" > "${tmp}"
    fi
  else
    render_http_only "${domain}" "${port}" "${auth_block}" "${extra_blocks}" > "${tmp}"
  fi

  install -m 0644 "${tmp}" "${conf}"
  ln -sfn "${conf}" "${NGINX_ENABLED}/${domain}.conf"
  rm -f "${tmp}"
done < "${NORMALIZED_CSV}"

if [[ -f "${MANIFEST}" ]]; then
  while IFS= read -r old_domain; do
    [[ -z "${old_domain}" ]] && continue
    if [[ -z "${desired_domains[$old_domain]+x}" ]]; then
      conf="${NGINX_AVAIL}/${old_domain}.conf"
      if [[ -f "${conf}" ]] && grep -q "${MARKER}" "${conf}"; then
        rm -f "${conf}" "${NGINX_ENABLED}/${old_domain}.conf"
      fi
    fi
  done < "${MANIFEST}"
fi

{
  for domain in "${desired_list[@]}"; do
    printf '%s\n' "${domain}"
  done
} | sort -u > "${MANIFEST}"

nginx -t
systemctl reload nginx
