#!/usr/bin/env bash
set -euo pipefail

CSV="${1:-/etc/app-map.csv}"
STATE_DIR="/var/lib/vps-bootstrap"
NGINX_AVAIL="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"
PROJECT_AUTH_DIR="/etc/nginx/project-auth"
MARKER="# generated by vps-bootstrap"
MANIFEST="${STATE_DIR}/app-sync.manifest"
ACME_ROOT="/var/www/html"
CUSTOM_CERT_ROOT="/etc/vps-custom-certs/projects"

mkdir -p "${STATE_DIR}"

declare -A desired_domains=()
declare -a desired_list=()

auth_block_for_domain() {
  local domain="$1"
  local auth_file="${PROJECT_AUTH_DIR}/${domain}.htpasswd"
  if [[ -s "${auth_file}" ]]; then
    cat <<EOF
    auth_basic "Project access";
    auth_basic_user_file ${auth_file};
EOF
  fi
}

render_http_only() {
  local domain="$1"
  local port="$2"
  local auth_block="$3"
  cat <<EOF2
${MARKER}
server {
    listen 80;
    server_name ${domain};
    client_max_body_size 50m;
${auth_block}
    location /.well-known/acme-challenge/ {
        auth_basic off;
        root ${ACME_ROOT};
    }

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
    }
}
EOF2
}

render_https() {
  local domain="$1"
  local port="$2"
  local auth_block="$3"
  local cert_path="$4"
  local key_path="$5"
  cat <<EOF2
${MARKER}
server {
    listen 80;
    server_name ${domain};
    client_max_body_size 50m;

    location /.well-known/acme-challenge/ {
        auth_basic off;
        root ${ACME_ROOT};
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name ${domain};
    client_max_body_size 50m;
${auth_block}
    ssl_certificate ${cert_path};
    ssl_certificate_key ${key_path};

    location /.well-known/acme-challenge/ {
        auth_basic off;
        root ${ACME_ROOT};
    }

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
    }
}
EOF2
}

cert_email_args=()
if [[ -n "${ACME_EMAIL:-}" ]]; then
  cert_email_args=(-m "${ACME_EMAIL}")
else
  cert_email_args=(--register-unsafely-without-email)
fi

while IFS=, read -r domain port type https; do
  [[ -z "${domain:-}" ]] && continue
  [[ "${domain}" == "domain" ]] && continue
  [[ "${domain:0:1}" == "#" ]] && continue

  domain="${domain//$'\r'/}"
  port="${port//$'\r'/}"
  type="${type//$'\r'/}"
  https="${https//$'\r'/}"

  if ! [[ "${domain}" =~ ^[A-Za-z0-9.-]+$ ]]; then
    echo "[WARN] Skipping invalid domain: ${domain}" >&2
    continue
  fi

  if ! [[ "${port}" =~ ^[0-9]+$ ]]; then
    echo "[WARN] Skipping ${domain} due to invalid port: ${port}" >&2
    continue
  fi

  desired_domains["${domain}"]=1
  desired_list+=("${domain}")

  conf="${NGINX_AVAIL}/${domain}.conf"
  tmp="$(mktemp)"
  auth_block="$(auth_block_for_domain "${domain}")"
  custom_cert_dir="${CUSTOM_CERT_ROOT}/${domain}"
  custom_cert="${custom_cert_dir}/fullchain.pem"
  custom_key="${custom_cert_dir}/privkey.pem"

  if [[ "${https,,}" == "yes" ]]; then
    cert_ready="no"
    cert_source=""
    if [[ -s "${custom_cert}" && -s "${custom_key}" ]]; then
      cert_ready="yes"
      cert_source="custom"
    elif [[ ! -s "/etc/letsencrypt/live/${domain}/fullchain.pem" ]]; then
      if certbot certonly \
        --webroot \
        -w "${ACME_ROOT}" \
        -d "${domain}" \
        --non-interactive \
        --agree-tos \
        "${cert_email_args[@]}" \
        --keep-until-expiring; then
        cert_ready="yes"
        cert_source="letsencrypt"
      else
        echo "[WARN] TLS issuance failed for ${domain}; keeping HTTP only for now" >&2
      fi
    else
      cert_ready="yes"
      cert_source="letsencrypt"
    fi

    if [[ "${cert_ready}" == "yes" ]]; then
      if [[ "${cert_source:-}" == "custom" ]]; then
        render_https "${domain}" "${port}" "${auth_block}" "${custom_cert}" "${custom_key}" > "${tmp}"
      else
        render_https "${domain}" "${port}" "${auth_block}" "/etc/letsencrypt/live/${domain}/fullchain.pem" "/etc/letsencrypt/live/${domain}/privkey.pem" > "${tmp}"
      fi
    else
      render_http_only "${domain}" "${port}" "${auth_block}" > "${tmp}"
    fi
  else
    render_http_only "${domain}" "${port}" "${auth_block}" > "${tmp}"
  fi

  install -m 0644 "${tmp}" "${conf}"
  ln -sfn "${conf}" "${NGINX_ENABLED}/${domain}.conf"
  rm -f "${tmp}"
done < "${CSV}"

if [[ -f "${MANIFEST}" ]]; then
  while IFS= read -r old_domain; do
    [[ -z "${old_domain}" ]] && continue
    if [[ -z "${desired_domains[$old_domain]+x}" ]]; then
      conf="${NGINX_AVAIL}/${old_domain}.conf"
      if [[ -f "${conf}" ]] && grep -q "${MARKER}" "${conf}"; then
        rm -f "${conf}" "${NGINX_ENABLED}/${old_domain}.conf"
      fi
    fi
  done < "${MANIFEST}"
fi

{
  for domain in "${desired_list[@]}"; do
    printf '%s\n' "${domain}"
  done
} | sort -u > "${MANIFEST}"

nginx -t
systemctl reload nginx
